[package]
name = "subscription-renewal"
version = "0.0.1"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
subscription-logging = { path = "../subscription-logging" }
syncro-common = { path = "../../common" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
proptest = { workspace = true }
subscription-logging = { path = "../subscription-logging" }
